### PR TITLE
Path component will now emit a 'started' event so long as a valid path was found

### PR DESCRIPTION
**Pull request by beyond-code-github**

### CODE REVIEW

**Comment by Irrelon** [comment]
Thanks for this pull request. 👍

**Comment by Irrelon** [comment]
Gonna modify the code slightly so we are not implicitly hoisting the startPoint variable.

**Comment by beyond-code-github** [comment]
Thanks @Irrelon! While I was in this space I spotted a bug with the PathComponent whereby a change to the speed while path is active is not handled correctly. Is this anything you are already aware of or shall I open a new issue to discuss options?

**Comment by Irrelon** [comment]
@beyond-code-github Wasn't aware, let's work out how to fix!

**Pull request merged**
