### PR TITLE
Update IgeEntity.js

### PR DESCRIPTION
**Pull request by zinne**

### CODE REVIEW

**Comment by raldred** [comment]
What are you trying to do, You've made over 8000 changes.

**Comment by zinne** [comment]
8000? Yes, I just copied the whole method out of my IDE. The change is just a single line that I have to change on my current Project. On line1835 I added the camera scale values
ctx.translate(-ige._currentCamera._translate.x * ige._currentCamera._scale.x, -ige._currentCamera._translate.y * ige._currentCamera._scale.y);

So when I have the time I can do a perfect formated pull request... maybe sometime :-)

**Comment by Irrelon** [comment]
@zinne GitHub has a built-in editor so you can edit files without having to use an IDE or other text editor that sometimes messes with whitespace and causes these sorts of issues.

So the change you made, can you explain what it is for and why it is needed? Really appreciate your time to update the file for others' benefit, just need to understand what the change is for so we can determine what effect it will have on the source.

Cheers!

**Comment by raldred** [comment]
I concur with @Irrelon we appreciate the contribution but we cannot merge the commit attached because it has >8000 deltas, this means we lose 
screenshot 2016-06-16 09 59 53

I recommend preventing your IDE from automatically correcting formatting when contributing on open source projects, Like you, I & other contributors, everyone has their preferred choice of formatting normally but you should always adhere to the existing system employed by the project you're contributing to.

I sorry if this feels like a lecture, I'm just trying to help 👍

**Pull request closed without merging**
