### PR TITLE
1.5.9

### PR DESCRIPTION
**Pull request by tsungche**

### CODE REVIEW

**Comment by Irrelon** [comment]
Whaaat? Why has this been opened as a pull request? No description... second time this has happened today...

**Comment by raldred** [comment]
I'd close, looks like someone doesn't know how to use pull requests.
They've deleted a load of stuff.

**Comment by Irrelon** [comment]
@raldred Agreed.

**Comment by raldred** [comment]
@tsungche you don't appear to have made any changes in this request.

**Pull request closed without merging**
