### PR TITLE
Fix for composite aabb rects being too large and misaligned

### PR DESCRIPTION
**Pull request by beyond-code-github**

### CODE REVIEW

**Comment by Irrelon** [comment]
Hey dude! Thanks for the PR. Is this definitely correct? Looks like it modifies inverse mode?

**Comment by beyond-code-github** [comment]
I believe so... it took me an age to track down and in the end I only figured it out because I was playing around in the Editor Component and I saw the bounding box suddenly change size and right itself when I made a change in the property editor!

I compared the implementation in the composite cache with the code the editor uses in the viewport to draw the bounding rectangle and this is what I came up with. The main difference was that the children aabb settings were not being recalculated at any point and this meant that combineRects was working on dodgy data and coming out with odd stuff.

Testing with displayCompositeBounds turned on shows what I would expect now, however I don't profess to understand about the inverse aspect of things. I only modified that as it matched the editor/viewport implementation so could well have had an impact elsewhere. If needed I can provide screenshots or sample code showing the difference.

**Comment by beyond-code-github** [comment]
https://github.com/Irrelon/ige/blob/stable/engine/core/IgeViewport.js#L386

**Comment by Irrelon** [comment]
Hmm, should be ok. If I notice something weird I'll revisit the inverse mode but let's proceed with this :)

**Comment by beyond-code-github** [comment]
Thanks for the swift turnaround on this and the others :)

What's the best method of getting hold of you these days by the way? I've been doing some fun stuff performance wise lately and would love to talk it through some time. I'm guessing you're not always logged in to twitter

**Comment by beyond-code-github** [comment]
It could be fun to set up an Isogenic Slack or Gitter perhaps now I think about it

**Comment by Irrelon** [comment]
Haha! Almost never visit twitter - never really seen the point of twitter to be honest, but could just be me getting old :). Best comms channel is probably iMessage/Text (07880790601) or email (rob@irrelon.com)

**Pull request merged**
